apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-workload-registrar
  namespace: spire
data:
  registrar.conf: |
    log_level = "debug"
    mode = "reconcile"
    trust_domain = "oidc.dlorenc.dev"
    server_socket_path = "/run/spire/sockets/registration.sock"
    agent_socket_path = "/run/spire/sockets/agent.sock"
    cluster = "demo-cluster"
    # enable label based registration:
    pod_label = "tekton.dev/taskRun"
    metrics_addr = ":8082"
